name: 独狼刺
encoding: utf-8

# permalink: pretty
permalink: /articles/:year/:month/:day/:title/

# Setup
title: 独狼刺

author:
  name: '独狼刺'

paginate: 5
excerpt_separator: "\n\n"

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['fenced_code_blocks']
