name: ChenGuangqi (陈广歧)
encoding: utf-8

# permalink: pretty
permalink: /articles/:year/:month/:day/:title/

# Setup
title: Chen Guangqi

author:
  name: 'Chen Guangqi'

paginate: 5
excerpt_separator: "\n\n"

markdown: kramdown
highlighter: pygments
redcarpet:
  extensions: ['fenced_code_blocks']
