name: ChenGuangqi (陈广歧)
encoding: utf-8

permalink: pretty

# Setup
title: Chen Guangqi

author:
  name: 'Chen Guangqi'

paginate: 5

markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ['fenced_code_blocks']
